name: Github Action

on:
  push:
    branches: ["main"]
  workflow_dispatch:
    inputs:
      deploy:
        description: 'Deploy manually'
        required: false

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install Dependencies
        run: npm ci
      - name: Build Project
        run: npm run build
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: ./build  

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ needs.build.outputs.artifacts_location }}/build

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: build
          path: ./downloaded-artifact

      - name: Deploy to Github pages
        if: github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && github.ref == 'refs/heads/main')
        run: vercel deploy ./downloaded-artifact --prod --confirm
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

# Manual deployment job
  manual-deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.deploy == 'true'
    steps:
      - name: Manual Deployment
        run: echo "This job runs manually for deployment"
