name: Deploy to Vercel

on:
  push:
    branches:
      - ashish

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Clear npm cache
      run: npm cache clean --force

    - name: Verify Node.js version
      run: node --version

    - name: Install Vercel CLI
      run: npm install -g vercel

    - name: Verify Vercel CLI version
      run: vercel -v

    - name: Set up Vercel project
      run: vercel --confirm --prod react-deployment-stage

    - name: Deploy to Vercel
      run: vercel --prod ${{ secrets.VERCEL_PROJECT_NAME }}
      env:
        VERCEL_PROJECT_NAME: react-deployment-stage
