name: Deploy to Vercel

on:
  push:
    branches:
      - ashish

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Vercel CLI
      run: npm install -g vercel

    - name: Deploy to Vercel
      run: vercel --prod ${{ secrets.VERCEL_PROJECT_NAME }}
      env:
        VERCEL_PROJECT_NAME: react-deployment-stage
